### ISSUE TITLE
Have you tried weighting the closer pixels higher?

### ISSUE THREAD

**Issue by Jules-A** [Artoriuz/glsl-chroma-from-luma-prediction#10]
I've done some quick tests weighting the closer pixels higher and results have been rather promising subjectively.

**Comment by Artoriuz** [comment]
Can you elaborate? Weight them higher where? How exactly?

**Comment by Jules-A** [comment]
> Can you elaborate? Weight them higher where? How exactly?

I guess you could technically say that by mixing with the 4tap it's already weighting the values to the closer pixels. However, it's not quite what I was thinking of.
I'm clueless as to how it should be done, however I think I saw something similar in SharpBilinear?
The test I did was just a dumb 3x the closest pixels and 2x the furthest and divide by the total amount.
What I was thinking was a much subtle amount and gradual weighting depending on distance.

**Comment by Jules-A** [comment]
@Artoriuz  If you are wondering what I was talking about with this, this is a half-assed way of doing but still has a bit more overhead than 12+4: https://pastebin.com/raw/3vMrfwJy

Tested in MPV with the same settings from your blog with the 420 test video (image) from your blog's github at 1440p.
12+4+8 (linked above): 
PSNR: 43.2218
DSSIM: 0.127729
MAE: 122.214 (0.00186486)
![mpv-shot0001](https://github.com/Artoriuz/glsl-chroma-from-luma-prediction/assets/1760158/6bef8c97-07d2-419b-8acc-d811c0fb75da)

12 (master)
PSNR: 42.9659
DSSIM: 0.12791
MAE: 125.663 (0.0019175)
![mpv-shot0001](https://github.com/Artoriuz/glsl-chroma-from-luma-prediction/assets/1760158/450febea-dbc0-43b6-a78a-eaa8d1ede505)

12+4 (master)
PSNR: 43.0025
DSSIM: 0.127894
MAE: 124.984 (0.00190713)
![mpv-shot0001](https://github.com/Artoriuz/glsl-chroma-from-luma-prediction/assets/1760158/1a31ed9c-c538-43ba-a2a4-ed0afcf889c9)

It looked better (subjectively) when I tried it the first time but it was way more costly performance wise and I forgot how I did it anyway.

**Comment by Jules-A** [comment]
@Artoriuz You added some 8 tap variants but why those choice of co-ords? I was referring to 1, 4, 5, 6, 9, 10, 11, 14 (in the current cfl). I added it as an extra with 50% weight of the 8 taps, and the total of 8taps at 45% of weight vs 12 tap and was seeing some good results, notably it seemed to reduce aliasing so I could get similar results to 1.0 AR on the old filter at just 0.8.
