### ISSUE TITLE
Can be used on vo=libmpv?

### ISSUE THREAD

**Issue by rainlycoris** [Artoriuz/glsl-chroma-from-luma-prediction#15]
Can not run in vo=libmp, is there any plan for support? Thank you very much!

**Comment by hooke007** [comment]
https://github.com/Artoriuz/glsl-chroma-from-luma-prediction/issues/8

**Comment by rainlycoris** [comment]
Maybe https://github.com/Artoriuz/glsl-chroma-from-luma-prediction/commit/ddd460698e732c7eddb674fdfbc11eba1993e90e remove linearize and delinearize.Now can be used on vo=gpu, but still cannot be used on vo=libmpv. Sorry for adding duplicate questions.

**Comment by hooke007** [comment]
You could post the log for others to check.

**Comment by rainlycoris** [comment]
[log.txt](https://github.com/user-attachments/files/16723887/log.txt)

```
vo = libmpv
gpu-context = macvk
hwdec = no
glsl-shaders = "~~/shaders/CfL_Prediction_Lite.glsl"
```
This is the partial output of the terminal.
```
[libmpv_render] fragment shader compile log (status=0):
[libmpv_render] ERROR: 0:95: '{' : syntax error: syntax error
[libmpv_render] 
[libmpv_render] shader link log (status=0): ERROR: One or more attached shaders not successfully compiled
[libmpv_render] 
```

**Comment by hooke007** [comment]
macvk is supported by vulkan api. Not opengl (vo=libmpv)

**Comment by rainlycoris** [comment]
[log.txt](https://github.com/user-attachments/files/16724149/log.txt)
I removed `gpu-context = macvk`, the result is still the same.
vo=gpu works but vo=libmpv doesn't.

**Comment by hooke007** [comment]
> the result is still the same.

Of course because you have set the vo.
The macvk should be worked with `gpu-next`

**Comment by rainlycoris** [comment]
I see what you mean, thank you. I mainly use iina, so I want to get support from libmpv.

**Comment by rainlycoris** [comment]
I solved the problem,don't use the initializer list and multidimensional array.
