### ISSUE TITLE
Color fringing artifacts

### ISSUE THREAD

**Issue by simonlui** [Artoriuz/glsl-chroma-from-luma-prediction#2]
Hi,

Thanks for making the shader. I am enjoying it a lot but I am seeing some color fringing I am not seeing with other shaders like KrigBilateral.

See below, for example and sorry for the large size images. I present the following scene with the CfL shader on.

![SubsPlease  Sousou no Frieren - 03 (1080p) 7EF3F175 mkv-00 03 10 566-#1](https://github.com/Artoriuz/glsl-chroma-from-luma-prediction/assets/502929/b9b063e1-b216-405e-a3e2-a5874fd0bdf5)

Notice the color fringing around the neckline of the nightgown the elf is wearing and the collarbone region? I am not seeing that with KrigBilateral in the same scene.

![SubsPlease  Sousou no Frieren - 03 (1080p) 7EF3F175 mkv-00 03 10 691-#1](https://github.com/Artoriuz/glsl-chroma-from-luma-prediction/assets/502929/3b629c50-5d31-40b1-99a9-a5bdeaeb9f96)

Maybe some tweaking of values is needed to avoid situations like this? Not sure what solution is feasible here. But this is coming up like once every minute for me while watching this content and does get a little distracting.

**Comment by Artoriuz** [comment]
Which variant of the shader are you using? Also are you up to date? I've made many changes recently.

**Comment by Artoriuz** [comment]
Nevermind, I can reproduce this. The 4-tap regression is too aggressive:
![4tap](https://github.com/Artoriuz/glsl-chroma-from-luma-prediction/assets/12078193/a3bd8382-9afb-4a6a-bbea-feef8b67f237)

It doesn't happen with the 12-tap regression only:
![12tap](https://github.com/Artoriuz/glsl-chroma-from-luma-prediction/assets/12078193/f2e7c1c9-c1f5-49df-8baf-f8564b0a06da)

The fix for this would be improving the mixing logic, I'll see what I can do later. Thanks =).

**Comment by Artoriuz** [comment]
Can you retest with the latest commit? Some colour fringing is unavoidable in this scene since part of it comes from the source, but I think the shader is doing a decent enough job now:
![mpv-shot0001](https://github.com/Artoriuz/glsl-chroma-from-luma-prediction/assets/12078193/03861c44-4c4a-4704-9d0c-aca5ec92b5b5)

**Comment by simonlui** [comment]
It is improved but there are still some sections of this scene with noticeable color fringing with the mix variant. This was seen in other scenes later as well when I went to retest and they exhibited similar improvements but still some issues.

![SubsPlease  Sousou no Frieren - 03 (1080p) 7EF3F175 mkv-00 03 09 231-#1](https://github.com/Artoriuz/glsl-chroma-from-luma-prediction/assets/502929/d7be7016-34d0-4bdb-9e70-dad1c6be18a8)

I will have to disagree that the original scene had color fringing. See below for the a screenshot without any chroma upscale shaders.

![SubsPlease  Sousou no Frieren - 03 (1080p) 7EF3F175 mkv-00 03 09 231-#2](https://github.com/Artoriuz/glsl-chroma-from-luma-prediction/assets/502929/638e296f-91f5-4275-9e09-22349c6164b9)

To see it better, 400% zoom via upscale and crop to that area. CfL first.

![nightgown_cfl](https://github.com/Artoriuz/glsl-chroma-from-luma-prediction/assets/502929/98d305a2-72a1-4cd6-90c4-08302eb790d5)

And the original

![nightgown_original](https://github.com/Artoriuz/glsl-chroma-from-luma-prediction/assets/502929/5a910cda-3dda-4aed-98fc-44d47eb1bcf5)

The 12-tap regression variant does play this perfectly like the original, so I might just stick with that to avoid this.

![SubsPlease  Sousou no Frieren - 03 (1080p) 7EF3F175 mkv-00 03 09 231-#3](https://github.com/Artoriuz/glsl-chroma-from-luma-prediction/assets/502929/3564995a-97db-4493-a1b0-b8e8f0263ce6)

**Comment by Artoriuz** [comment]
I mean, I can clearly see the colour going from green to red in the "original" screenshot, that's fringing. The shader is just making it way worse, but as you noted the 12-tap variant is fine.

I'll keep trying to find a solution for this, but everything I've tried has a negative effect on how detailed the shader can be. For now I think it's mostly safe to use the 12-tap variant if you want to avoid the worst artifacts like this one. That has been reflected in the readme as well.

**Comment by simonlui** [comment]
Okay, that is fine. I'll close the issue since I am fine with using the 12-tap regression variant in place of the mixed variant. Thanks for taking a look at this.

**Comment by simonlui** [comment]
I downloaded the latest shader you put up today and the regular mixed variant now no longer exhibits the issue as much as before and I would say it's to the extent I would say it's solved even though yes, you can pixel peep and pick out some enhanced fringing compared the original. Thanks a lot again.

![SubsPlease  Sousou no Frieren - 03 (1080p) 7EF3F175 mkv-00 03 09 231-#4](https://github.com/Artoriuz/glsl-chroma-from-luma-prediction/assets/502929/e6822d64-1a03-4962-b004-2dbb944c1577)
