### ISSUE TITLE
Loss of detail on reds on darker backgrounds

### ISSUE THREAD

**Issue by Jules-A** [Artoriuz/glsl-chroma-from-luma-prediction#5]
Original:
![z](https://user-images.githubusercontent.com/1760158/273390875-6004d033-d1ef-4d4f-873c-f60379248a60.PNG)

12:
![Capture](https://github.com/Artoriuz/glsl-chroma-from-luma-prediction/assets/1760158/3ba629ec-02d8-4177-9ca1-841a049aeb08)

Reds become extremely bright and vary way too much from source and lose any borders or shadowing when on darker backgrounds.

Source: to-love-ru-darkness - S3E2 @ 6:57 but I've noticed it in many other areas to a lesser extent.

**Comment by Artoriuz** [comment]
Not sure if I follow what the problem here is, is it that the red characters seem brighter and more saturated on top of the blue background?

Does it happen on all variants?

Does it happen with something like lanczos?

**Comment by Jules-A** [comment]
> Not sure if I follow what the problem here is, is it that the red characters seem brighter and more saturated on top of the blue background?

You really can't see it? I thought it was obvious :/ The top half numbers/letters on the board from the part where the white turns to blue is completely off and disjointed from the bottom half's colours that it looks fake. The numbers on the right are also extremely bright.

> Does it happen on all variants?

Yes, though I think it's ever so slightly better on the mix/4 variants.

> Does it happen with something like lanczos?

Lanczos is terrible compared to kaiser/catrom ect. for cscale but no, none of the inbuilt chroma scalers exhibit that behavior. Some have way more black/darkness than there should be but none I've found are so bright.

Lanczos:
![image](https://github.com/Artoriuz/glsl-chroma-from-luma-prediction/assets/1760158/78fab03b-ac0f-4d82-8eb5-c43fbf5a013e)

If you switch between chroma scalers you can't miss it...

There's also a large amount of ringing going on in 12 (don't think it's noticeable using AR from Ravu) though I can't really see it in mixed.

**Comment by Artoriuz** [comment]
I can see it, but I can also see in all of your screenshots. This doesn't seem to be CfL-specific (albeit it does make the difference more obvious), can you please check what Krig does in the same scene?

**Comment by Jules-A** [comment]
> I can see it, but I can also see in all of your screenshots. This doesn't seem to be CfL-specific (albeit it does make the difference more obvious), can you please check what Krig does in the same scene?

Huh? what do you mean? It's not happening with Lanczos or any of the others I've tested and I don't recall it occurring when I tested Krig before, will retest without fsrcnnx though now.

EDIT: It also appears in Krigbillateral but the colours are slightly better... Krig has a separate bug here of being misaligned (too far to the south east).

Krigbillateral: 
![image](https://github.com/Artoriuz/glsl-chroma-from-luma-prediction/assets/1760158/8b6d7caf-f3d6-4bab-86da-18b7d45b7614)

It does NOT occur with https://github.com/Artoriuz/glsl-chroma-from-luma-prediction/commit/9ad91ab1bc94dfe52a763755b15a02a7ecca4264 :

![image](https://github.com/Artoriuz/glsl-chroma-from-luma-prediction/assets/1760158/bec571a0-e75f-47c4-9dc8-8c809024df27)

**Comment by Artoriuz** [comment]
Just look at the red "8", the top half looks more saturated on all screenshots you've sent so far. If that's not the issue you're talking about then I'm seeing something else.

**Comment by Jules-A** [comment]
> Just look at the red "8", the top half looks more saturated on all screenshots you've sent so far. If that's not the issue you're talking about then I'm seeing something else.

Yes, I guess it is saturation.
Some is to be expected when upscaling but Cfl and to a slightly lesser extent, Krig's is changing the color way too much compared to inbuilt scalers and even a previous version of Cfl... to the point it easily stands out and looks wrong.
For a quick rgb comparison from the top of the 8 (probably the most noticeable part) testing from a part that doesn't have blacks leaking from the outline:
```
Original
208
72
82

Cfl 12
245
51
56

Cfl old
230
68
77
```

**Comment by Jules-A** [comment]
Hmm.. It's not specific to reds, it seems to make blues a lot brighter too (though this is 480p source where errors are more acceptable):
Hamming (pretty much same as original):
![hamming](https://github.com/Artoriuz/glsl-chroma-from-luma-prediction/assets/1760158/04719421-e82b-4b0f-b2c6-0074e9f2876f)

Mix
![mix](https://github.com/Artoriuz/glsl-chroma-from-luma-prediction/assets/1760158/c9b33cb0-ec7c-461f-8e12-9cc716bc2dbd)

Actually, come to think about it, the whole image could be becoming brighter, didn't check it.

**Comment by Artoriuz** [comment]
I'm not super convinced this is a legitimate issue. The shader can't be compared to normal scalers in this case if you want to know what's the expected output, you'd have to find a 4:4:4 reference and test it after chroma subsampling.

**Comment by Jules-A** [comment]
> I'm not super convinced this is a legitimate issue. The shader can't be compared to normal scalers in this case if you want to know what's the expected output, you'd have to find a 4:4:4 reference and test it after chroma subsampling.

Idk, really depends on what you want the shader to be, something that disregards the source colouring to look subjectively better or something more accurate I guess. The differences aren't really too subtle and are quite noticeable on normal playthrough for me.

I don't have any good 4:4:4 reference videos but some quick tests on 4:4:4 images I wasn't really able to replicate it, it did look a decent bit too bright and too dark in some areas but not really anything too noticeable.

**Comment by Artoriuz** [comment]
>Idk, really depends on what you want the shader to be, something that disregards the source colouring to look subjectively better or something more accurate I guess.

No. My point is that you don't know what the "source colour" is unless you have a 4:4:4 reference.

**Comment by Jules-A** [comment]
> No. My point is that you don't know what the "source colour" is unless you have a 4:4:4 reference.

Well yeah that's true but it's doubtful that the authors would put such odd colours and that none of the built-in more tried scalers exhibit the same issue.

**Comment by Artoriuz** [comment]
The built-in scalers are merely interpolating the existing data points, which have nothing to do with what the authors intended to show. Chroma-subsampling is done for compression, not artistic intent.

I'm not saying CfL 100% isn't overshooting a bit, it probably is, but you don't know by _how much_ unless you have a 4:4:4 reference.

**Comment by Artoriuz** [comment]
Case in point:

lanczos (mpv default):
![lanczos](https://github.com/Artoriuz/glsl-chroma-from-luma-prediction/assets/12078193/561e1b3a-5f14-4763-9d3f-437f25d2ac5e)

cfl (12-tap,  master):
![cfl12](https://github.com/Artoriuz/glsl-chroma-from-luma-prediction/assets/12078193/1026ee92-8cc4-4aa1-a5ee-d6c9cf4aa54b)

cfl (12-tap,  smaller downsampling window for a sharper LUMA_LOWRES):
![cfl12_smaller_window](https://github.com/Artoriuz/glsl-chroma-from-luma-prediction/assets/12078193/91f5475c-6e5f-493e-9f45-54b1017c00a9)

Look at the blue spiral on top of the girl with white hair, you can see that the outline gets closer to what lanczos is doing with the sharper downsampling passes, but if you look at any of the coloured balls on top of coloured backgrounds (like the yellow one right next to her) you can see that master is doing a much better job at keeping the unintended colours away (you don't see yellow blending into purple nearly as much).

This could be a case of being better at one thing while being worse at another, but without the reference we literally can't tell.

**Comment by Jules-A** [comment]
That's a tough example since being lineart you can't tell if it's intended to be shown like that as anime often has drawing showing transparency.
Also I don't think lanczos is the best for comparison, while it is the default I don't feel lanczos does a very good job of chroma scaling from my subjective testing. Lanczos was one of the furthest away from the source colours out of the inbuilt scalers (so it's harder to spot the difference). Hamming feels it captures the colours much better and just feels way more natural though it's not too sharp like Cfl so without luma scaling kaiser might look better for the sharpness.

**Comment by Artoriuz** [comment]
Last commit should help with this.

**Comment by Jules-A** [comment]
It's a lot better but still feels little off imo.

**Comment by Jules-A** [comment]
Hmm... actually it's still pretty awful, I noticed some other reds got completely murdered and washed out yellows, the issue probably should be kept open... Forgot to screenshot it and forgot the anime/scene already.
It doesn't occur at all when running from CHROMA_SCALED (but that suffers from massive offset issues).

**Comment by Jules-A** [comment]
I've been playing around with swapping out FSR's approximated Lanczos with others like Hamming (reduces impact but not very sharp) and Garamond's modified versions of scalers from here: https://github.com/garamond13/alt-scale (which pretty much solves the issue and is far higher quality in general but 2x as slow...).

I'm going to try reducing the distance to see if that helps. EDIT: It does but causes other artifacts.

EDIT2: With those alt-scale shaders and replacing the FSR with the current one Cfl uses doesn't cause it so it's not it on it's own.

EDIT3: Actually, while it does look good, after testing Garamond scaling on it's own (in altScale) it appears to de-saturate the image so what's happening here is it's just undoing Cfl's over-saturation.

**Comment by I2ujbNGakP8KfLKbho0Z** [comment]
Another example (using the fullsize CfL shader):

Krig:
![agf_1_krig](https://github.com/Artoriuz/glsl-chroma-from-luma-prediction/assets/91436030/a2767252-ebb7-4547-94f8-92c0eddac79b)

CfL:
![agf_1_cfl](https://github.com/Artoriuz/glsl-chroma-from-luma-prediction/assets/91436030/0dfc6f9a-fbf2-4302-a418-117b40417eee)

The joystick in the middle of the frame loses its outline completely.
It'd be great if this can be fixed, because while this issue is present, rainbowing in MPEG2-streams is reduced immensely by this shader, which is why i want to use it.
Hope this helps!
