### ISSUE TITLE
Strange Chroma Offset

### ISSUE THREAD

**Issue by deus0ww** [Artoriuz/glsl-chroma-from-luma-prediction#7]
To reproduce: toggle CfL on/off and compare with cscale. There's a slight shift to the right.

**Possible Fix:**
Change:
```
//!HOOK CHROMA
//!BIND CHROMA
```
To:
```
//!HOOK CHROMA
//!BIND HOOKED
```
(Also functions like CHROMA_size -> HOOKED_size, etc)

Toggle CfL on/off and compare with cscale. There should be no shift.

I have no idea why this works.  MimeBilateral is also like this.

**Comment by Artoriuz** [comment]
I don't think `//!BIND CHROMA` vs `//!BIND HOOKED` is supposed to make a difference, but this probably a good practice either way so sure.

**Comment by deus0ww** [comment]
Did you noticed a shift with //!BIND CHROMA?

**Comment by Artoriuz** [comment]
Nope, the change made 0 difference in my test images.

**Comment by deus0ww** [comment]
Probably a difference between vo=gpu and vo=gpu-next.

**Comment by Jules-A** [comment]
I'm still getting a weird offset with master (on gpu-next) :/
