### ISSUE TITLE
artifacts after commit 93ac228

### ISSUE THREAD

**Issue by KOSHACHIJ** [Artoriuz/glsl-chroma-from-luma-prediction#8]
Intel MacBook, macOS 11, mpv 0.36.0, IINA 1.3.3 ( [config](https://github.com/KOSHACHIJ/mpv-config) )

after commit 93ac228 in mpv just blue screen and artifacts in IINA

mpv:
<img width="1440" alt="Screenshot 2023-10-24 at 13 53 40" src="https://github.com/Artoriuz/glsl-chroma-from-luma-prediction/assets/67644959/ef95c01b-9f0c-489c-9fe5-92f6116a9d20">

IINA after 93ac228:
<img width="1440" alt="Screenshot 2023-10-24 at 13 52 40" src="https://github.com/Artoriuz/glsl-chroma-from-luma-prediction/assets/67644959/4a58d288-c93c-4cc9-a39d-ad94edcfac79">

IINA after cbedcce:
<img width="1440" alt="Screenshot 2023-10-24 at 13 51 34" src="https://github.com/Artoriuz/glsl-chroma-from-luma-prediction/assets/67644959/4081539b-bfe2-47c9-9ac5-f6e4535183eb">

**Comment by deus0ww** [comment]
If you're not using vo=gpu-next, remove linearize and delinearize.

**Comment by Artoriuz** [comment]
Yeah, these functions are only available in gpu-next which I believe IINA literally can't use (libmpv limitation).

No idea about what's happening in the last screenshot though...

**Comment by KOSHACHIJ** [comment]
ty for answer, i still waiting for Metal version of gpu-next ))

**Comment by deus0ww** [comment]
If you want pre-modified shaders for vo=gpu/libmpv, try these:

https://github.com/deus0ww/mpv-conf/tree/master/shaders/bilateral

**Comment by rainlycoris** [comment]
> If you want pre-modified shaders for vo=gpu/libmpv, try these:
> 
> https://github.com/deus0ww/mpv-conf/tree/master/shaders/bilateral

This file is gone, now how do I modify the shader to support libmpv? Thanks.

I know that libmpv glsl does not use multidimensional arrays, is there any other problem?

**Comment by rainlycoris** [comment]
I solved the problem,don't use the initializer list.
